# Generated by Django 3.2.8 on 2022-01-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('provider_ID', models.TextField(default='null', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('tagProvider', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('stationProvider', models.CharField(max_length=30)),
                ('stationName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.TextField(primary_key=True, serialize=False)),
                ('tagID', models.TextField(max_length=9)),
                ('licenseYear', models.DecimalField(decimal_places=0, max_digits=4)),
                ('tagProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softeng.operator')),
            ],
        ),
    ]
