# Generated by Django 3.2.9 on 2021-12-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('tagID', models.IntegerField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('operatorDebited', models.IntegerField(max_length=10)),
                ('dateOfCharge', models.DateField()),
                ('vehicleID', models.IntegerField(max_length=10)),
            ],
        ),
    ]
