# Generated by Django 4.0 on 2022-01-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('provider_ID', models.TextField(default='null', max_length=4, primary_key=True, serialize=False, unique=True)),
                ('tagProvider', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('stationProvider', models.CharField(max_length=30)),
                ('stationName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.TextField(primary_key=True, serialize=False)),
                ('tagID', models.TextField(max_length=9)),
                ('providerAbbr', models.TextField(max_length=20)),
                ('licenseYear', models.DecimalField(decimal_places=0, max_digits=4)),
                ('tagProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softeng.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('passID', models.TextField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('vehicleRef', models.TextField(max_length=12)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stationRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softeng.station')),
            ],
        ),
    ]
