# Generated by Django 3.2.9 on 2021-12-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='operatorDebited',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='charge',
            name='tagID',
            field=models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='vehicleID',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
