# Generated by Django 3.2.8 on 2022-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('passID', models.TextField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('stationRef', models.TextField(max_length=4)),
                ('vehicleRef', models.TextField(max_length=12)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='operator',
            name='provider_ID',
            field=models.TextField(default='null', max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
