# Generated by Django 3.2.8 on 2021-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0002_auto_20211213_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
