# Generated by Django 3.2.8 on 2021-12-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0003_alter_charge_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operatorID', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.IntegerField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('startingDate', models.DateField()),
                ('column', models.DecimalField(decimal_places=0, max_digits=10)),
                ('operatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softeng.operator')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='operatorID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='softeng.operator'),
            preserve_default=False,
        ),
    ]
