# Generated by Django 3.2.8 on 2021-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0004_auto_20211213_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operatorID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='password',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True),
        ),
    ]
