# Generated by Django 3.2.8 on 2021-12-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0005_auto_20211213_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='abriviation',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.TextField(primary_key=True, serialize=False)),
                ('tagID', models.TextField(max_length=9)),
                ('licenseYear', models.DecimalField(decimal_places=0, max_digits=4)),
                ('tagProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softeng.operator')),
            ],
        ),
    ]
