# Generated by Django 3.2.8 on 2021-12-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0005_auto_20211213_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='operatorID',
            new_name='foperator',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='operatorID',
            new_name='foperator',
        ),
    ]
