# Generated by Django 3.2.8 on 2021-12-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0006_auto_20211213_1029'),
        ('softeng', '0006_auto_20211213_1228'),
    ]

    operations = [
    ]
