# Generated by Django 4.0 on 2021-12-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0007_merge_0006_auto_20211213_1029_0006_auto_20211213_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationID', models.TextField(primary_key=True, serialize=False)),
                ('stationProvider', models.CharField(max_length=30)),
                ('stationName', models.TextField(max_length=30)),
            ],
        ),
    ]
