# Generated by Django 4.0 on 2021-12-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0008_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='stationName',
            field=models.CharField(max_length=30),
        ),
    ]
