# Generated by Django 4.0 on 2021-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softeng', '0010_alter_station_stationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
